# Generated by Django 4.1 on 2024-07-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCategory',
            fields=[
                ('category_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('item_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('price', models.IntegerField(max_length=11)),
                ('stock', models.IntegerField(max_length=11)),
                ('recomended', models.IntegerField(max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingcategory')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchase',
            fields=[
                ('purchase_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=256)),
                ('booked_date', models.DateTimeField()),
                ('cancel', models.IntegerField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=11)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingpurchase')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItemsincart',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=11)),
                ('booked_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
    ]
