# Generated by Django 4.1 on 2024-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.IntegerField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'accoun_user',
            },
        ),
        migrations.CreateModel(
            name='AdministratorAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
    ]
