# Generated by Django 4.1 on 2024-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
