# Generated by Django 4.1 on 2024-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
    ]
